### ISSUE TITLE
Media Files sync is not shown in Migrate DB

### ISSUE THREAD

**Issue by elbsurfer** [wp-sync-db/wp-sync-db-media-files#10]
Hello,
I installed the WP Sync DB first and the Media Extension after it, when I go to Tools -> Migrate DB - I can not see the option to include media files ... does anyone has an idea?

**Comment by thefill** [comment]
Same here mate ;-/

**Comment by slang800** [comment]
duplicate of https://github.com/wp-sync-db/wp-sync-db/issues/16, perhaps?

**Comment by shanecarmody** [comment]
Yeah I had the same issue. I would say that this is a duplicate, right @thefill @elbsurfer ? 

:+1: great plugin

**Comment by elbsurfer** [comment]
Yes, it shows up on my side when I enter the connection details of the page I want to pull from. So everything is good! I close this one.
