### ISSUE TITLE
Media Option not showing in Advanced Options

### ISSUE THREAD

**Issue by Dijkie** [wp-sync-db/wp-sync-db-media-files#11]
Hello,

First of all thanks for sharing.
After I activated WP Sync DB and WP Sync DB Media Files the option of the alst one are not showing up in the Advanced Options section of the WP Sync.

I must do something wrong.

Can you please help me.

Best regards,

Martijn

**Comment by slang800** [comment]
duplicate of #10 /  wp-sync-db/wp-sync-db#16?

**Comment by Dijkie** [comment]
Thanks!
