### ISSUE TITLE
Few images not pulling from server to local machine

### ISSUE THREAD

**Issue by jeffal** [wp-sync-db/wp-sync-db-media-files#12]
Hello,

Thank you for creating this wonderful plugin!

Is there a reason why all of my images are not transferring? I am pulling from a development server to my local machine. The development server has 391 items, while my local machine only has 387 items.

I have tried the pull a few times, regenerated thumbnails, modified permissions, etc.

If anyone can think of something else I can try, it would be greatly appreciated!

Thanks,
Jeff

**Comment by slang800** [comment]
are you getting that total number of items from wordpress itself, or from the filesystem?

**Comment by jeffal** [comment]
As I recall, the total number of items was from wordpress itself.
