### ISSUE TITLE
Release 1.1.4b1 is broken, new release required

### ISSUE THREAD

**Issue by philcook** [wp-sync-db/wp-sync-db-media-files#15]
I was using the zip of release 1.1.4b1 and was struggling to get this to work and dug into the code and found the issue in asset/js/script.js with this in my console.
`Uncaught ReferenceError: wpsdb_parse_json is not defined`

However after reviewing the updates to this file in the master branch you have already fixed this issue which I can confirm from testing.

Could I please ask that you make a new release so no-one else falls foul of this.

Many thanks.

**Comment by slang800** [comment]
thanks! pushed as v1.1.5
