### ISSUE TITLE
can't see media files checkbox

### ISSUE THREAD

**Issue by sb-lc** [wp-sync-db/wp-sync-db-media-files#26]
the checkbox 'Media Files' is not showing up in wp-sync-db settings

**Comment by notslang** [comment]
Read this issue: wp-sync-db/wp-sync-db#16. Is that what is happening?

**Comment by sb-lc** [comment]
yes it is, thanks

On 17/06/16 17:49, Sean Lang wrote:

Read this issue: wp-sync-db/wp-sync-db#16https://github.com/wp-sync-db/wp-sync-db/issues/16. Is that what is happening?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHubhttps://github.com/wp-sync-db/wp-sync-db-media-files/issues/26#issuecomment-226821334, or mute the threadhttps://github.com/notifications/unsubscribe/AI-zRQlM0VqoqWTjgj0ifgOxxudCSMF5ks5qMtAGgaJpZM4I3fiI.

  [LECOpenDay photo openday-june16-email-signature_zpsacndi86w.jpeg] https://leicestercollege.ac.uk/events/open-day-saturday-25-june-2016

https://leicestercollege.ac.uk/events/open-day-saturday-25-june-2016/

---

Please consider the environment before printing this e-mail.

---

This email and any associated files are confidential and intended   solely for the individual or entity to whom they are addressed. If the email is   incorrectly addressed or has been received in error please notify the sender and delete   the email, and any associated files immediately. If you are not the intended recipient   you must not use, disclose, copy, print or rely on this email and any attempt to do so   is prohibited and may be illegal.

Any views or opinions expressed in this email, and associated   files if any, are solely those of the author and do not necessarily represent those of   Leicester College.

Although we have taken precautions to ensure this email, and   associated files if any, are virus free we advise that it is the recipient's   responsibility to check to guarantee it is virus free.

---
