### ISSUE TITLE
Hanging on determining media to migrate

### ISSUE THREAD

**Issue by Podders** [wp-sync-db/wp-sync-db-media-files#7]
Hi,

I have an issue where the media sync is hanging when determining which files to transfer, nothing particularly special about the install, WP 4.0, WP Sync DB 1.5 and WP Sync DB Media Files 1.1.4b1,

Only option is to cancel out of the sync when it hangs,

![media-pull](https://cloud.githubusercontent.com/assets/3645985/4702336/30586e90-5862-11e4-9872-34b660127da7.jpg)

**Comment by slang800** [comment]
Closed by #9

**Comment by Podders** [comment]
Perfect,works like a charm, thanks :)
